services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    container_name: ${POSTGRES_CONTAINER_NAME}
    env_file:
      - .env.docker
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_PORT}"  # Bind host port to container port
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
